services:
  - type: web
    name: pcf-bilanzierung
    env: docker
    dockerfilePath: ./Dockerfile
    region: frankfurt
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pcf-postgres
          property: connectionString

databases:
  - name: pcf-postgres
    databaseName: pcf_db
    user: pcf_user
    plan: free
